// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solares.Data;

#nullable disable

namespace Solares.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230927141228_completed")]
    partial class completed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Solares.Data.WhyUsDesc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeIcon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WhyUsDesc");
                });

            modelBuilder.Entity("Solares.Models.Cookie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cookie");
                });

            modelBuilder.Entity("Solares.Models.DataShoot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataShoot");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den\r\nallgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht\r\nverpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach\r\nUmständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen.\r\nVerpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen\r\nGesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt\r\nder Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden.\r\nRechtsverletzungen werden wir diese Inhalte umgehend entfernen.",
                            Title = "Haftung für Inhalte"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss\r\nhaben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die\r\nInhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich.\r\nDie verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft.\r\nRechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente\r\ninhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer\r\nRechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige\r\nLinks umgehend entfernen.",
                            Title = "Haftung für Links"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem\r\ndeutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung\r\naußerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen\r\nAutors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht\r\nkommerziellen Gebrauch gestattet.\r\nSoweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte\r\nDritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie\r\ntrotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen\r\nentsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte\r\numgehend entfernen.\r\n\r\n\r\n\r\n Quelle: https://www.e-recht24.de/impressum-generator.html",
                            Title = "Urheberrecht"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Der Betreiber dieser Seiten nimmt den Schutz Ihrer persönlichen Daten sehr ernst. Wir behandeln\r\nIhre personenbezogenen Daten vertraulich und entsprechend der gesetzlichen\r\nDatenschutzvorschriften sowie dieser Datenschutzerklärung          \r\n\r\n\r\n    Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich.\r\nSoweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder E-MailAdressen) erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten\r\nwerden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben.\r\nWir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per EMail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch\r\nDritte ist nicht möglich.",
                            Title = "DATENSCHUTZERKLÄRUNG"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten zur Übersendung\r\nvon nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit\r\nwidersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der\r\nunverlangten Zusendung von Werbeinformationen, etwa durch Spam-E-Mails, vor.",
                            Title = "WIDERSPRUCH WERBE-MAILS"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sie haben jederzeit das Recht auf unentgeltliche Auskunft über Ihre gespeicherten\r\npersonenbezogenen Daten, deren Herkunft und Empfänger und den Zweck der Datenverarbeitung\r\nsowie ein Recht auf Berichtigung, Sperrung oder Löschung dieser Daten. Hierzu sowie zu weiteren\r\nFragen zum Thema personenbezogene Daten können Sie sich jederzeit unter der im Impressum\r\nangegebenen Adresse an uns wenden.",
                            Title = "AUSKUNFT, LÖSCHUNG, SPERRUNG"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Die Internetseiten verwenden teilweise so genannte Cookies. Cookies richten auf Ihrem Rechner\r\nkeinen Schaden an und enthalten keine Viren. Cookies dienen dazu, unser Angebot\r\nnutzerfreundlicher, effektiver und sicherer zu machen. Cookies sind kleine Textdateien, die auf Ihrem\r\nRechner abgelegt werden und die Ihr Browser speichert.\r\nDie meisten der von uns verwendeten Cookies sind so genannte „Session-Cookies“. Sie werden nach\r\nEnde Ihres Besuchs automatisch gelöscht. Andere Cookies bleiben auf Ihrem Endgerät gespeichert,\r\nbis Sie diese löschen. Diese Cookies ermöglichen es uns, Ihren Browser beim nächsten Besuch\r\nwiederzuerkennen.\r\nSie können Ihren Browser so einstellen, dass Sie über das Setzen von Cookies informiert werden und\r\nCookies nur im Einzelfall erlauben, die Annahme von Cookies für bestimmte Fälle oder generell\r\nausschließen sowie das automatische Löschen der Cookies beim Schließen des Browsers aktivieren.\r\nBei der Deaktivierung von Cookies kann die Funktionalität dieser Website eingeschränkt sein.",
                            Title = "COOKIES"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Der Provider der Seiten erhebt und speichert automatisch Informationen in so genannten Server-Log\r\nFiles, die Ihr Browser automatisch an uns übermittelt. Dies sind:\r\n    - Browsertyp/ Browserversion\r\n    - verwendetes Betriebssystem\r\n    - Referrer URL\r\n    - Hostname des zugreifenden Rechners\r\n    - Uhrzeit der Serveranfrage\r\n\r\nDiese Daten sind nicht bestimmten Personen zuordenbar. Eine Zusammenführung dieser Daten mit\r\nanderen Datenquellen wird nicht vorgenommen. Wir behalten uns vor, diese Daten nachträglich zu\r\nprüfen, wenn uns konkrete Anhaltspunkte für eine rechtswidrige Nutzung bekannt werden.",
                            Title = "SERVER-LOG-FILES"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Wenn Sie uns per Informationen über E-Mail via der Kontaktaufnahmefunktion zukommen lassen,\r\nwerden Ihre Angaben aus dem Anfrageformular inklusive der von Ihnen dort angegebenen\r\nKontaktdaten zwecks Bearbeitung der Anfrage und für den Fall von Anschlussfragen bei uns\r\ngespeichert. Diese Daten geben wir nicht ohne Ihre Einwilligung weiter.",
                            Title = "KONTAKTAUFNAHME"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Herrn M.Sc. Marcus Schmidt, Geschäftsführer\r\n\r\nHerrn M.Sc. Omar Almatar Aljarad, Geschäftsführer",
                            Title = "Geschäftsführung"
                        });
                });

            modelBuilder.Entity("Solares.Models.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeSendEmail")
                        .HasColumnType("datetime2");

                    b.Property<string>("body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("Solares.Models.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleDe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Home");
                });

            modelBuilder.Entity("Solares.Models.IMP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IMP");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ingenieurbüro Schmidt & Aljarad\r\nSoldier Str 32\r\nD-13359 Berlin",
                            Title = "Adresse"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Herr Marcus Schmidt\r\nHerr Omar Almatar Aljarad",
                            Title = "Vertreten durch:"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Herr Marcus Schmidt\r\nE-Mail: m.schmidt@eng-sa.de\r\nHandynummer: +49 1577 3606583\r\n\r\nHerr Omar Almatar Aljarad\r\nE-Mail: o.aljarad@eng-sa.de\r\nHandynummer:  +49 177 1413741\r\n\r\nEmail für :\r\n1. allgemeine Anfragen: info@eng-sa.de\r\n2. Medienvertretende: presse@eng-sa.de\r\n3. Rechnung: invoice@eng-sa.de",
                            Title = "Kontaktdaten"
                        },
                        new
                        {
                            Id = 4,
                            Description = "23/513/00364",
                            Title = "Steuernummer\r\n"
                        });
                });

            modelBuilder.Entity("Solares.Models.Localization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Localization");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            active = true
                        });
                });

            modelBuilder.Entity("Solares.Models.OurServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeIcon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OurServiceItem");
                });

            modelBuilder.Entity("Solares.Models.OurServiceTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleDe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OurServiceTitle");
                });

            modelBuilder.Entity("Solares.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdModal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("Solares.Models.ServiceTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleDe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTitle");
                });

            modelBuilder.Entity("Solares.Models.WhyUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleDe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WhyUs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
